version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql-5.7-container
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: invoice
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3309:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: